### ISSUE TITLE
Unable to install and run on Debian 10

### ISSUE THREAD

**Issue by shaunjstokes** [vertcoin-project/p2pool-vtc#48]
Not sure if this is a bug but since the P2Pool update for Verthash this doesn't work for me on Debian 10.

This step produces an error.
root@vtcp2pool:/usr/src/p2pool-vtc/lyra2re-hash-python# sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup, Extension

If I change 'from setuptools' to 'from distutils.core' in setup.py on line 1 this fixes that issue for me.

Then when trying to run P2pool there is another error:
root@vtcp2pool:/usr/src/p2pool-vtc# python run_p2pool.py --net vertcoin
Traceback (most recent call last):
  File "run_p2pool.py", line 3, in <module>
    from p2pool import main
  File "/usr/src/p2pool-vtc/p2pool/main.py", line 25, in <module>
    from . import networks, web, work
  File "/usr/src/p2pool-vtc/p2pool/networks/__init__.py", line 4, in <module>
    for module_loader, name, ispkg in pkgutil.iter_modules(__path__))
  File "/usr/src/p2pool-vtc/p2pool/networks/__init__.py", line 4, in <genexpr>
    for module_loader, name, ispkg in pkgutil.iter_modules(__path__))
  File "/usr/src/p2pool-vtc/p2pool/networks/bitcoin.py", line 1, in <module>
    from p2pool.bitcoin import networks
  File "/usr/src/p2pool-vtc/p2pool/bitcoin/networks/__init__.py", line 4, in <module>
    for module_loader, name, ispkg in pkgutil.iter_modules(__path__))
  File "/usr/src/p2pool-vtc/p2pool/bitcoin/networks/__init__.py", line 4, in <genexpr>
    for module_loader, name, ispkg in pkgutil.iter_modules(__path__))
  File "/usr/src/p2pool-vtc/p2pool/bitcoin/networks/vertcoin.py", line 10, in <module>
    import verthash
ImportError: No module named verthash

**Comment by vertiond** [comment]
Install the verthash python module manually
https://github.com/vertcoin-project/verthash-pospace

**Comment by shaunjstokes** [comment]
Thanks that worked although I also had to delete the vertcoin_testnet files to prevent memory errors and change the vertcoin.dat location in 'vertcoin.py'.

**Comment by vertiond** [comment]
It is easiest to symlink verthash.dat from your vertcoin-core folder to p2pool-vtc.
