### ISSUE TITLE
GNU/Linux Debian 11 - run_p2pool.py - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by blackmennewstyle** [vertcoin-project/p2pool-vtc#54]
```
python3 run_p2pool.py --help
Traceback (most recent call last):
  File "/home/ceedii/p2pool-vtc-3.0.0/run_p2pool.py", line 3, in <module>
    from p2pool import main
  File "/home/ceedii/p2pool-vtc-3.0.0/p2pool/__init__.py", line 43
    except Exception, e:
                    ^
SyntaxError: invalid syntax

```
I'm getting that error when i try to execute run_p2pool.py

**Comment by blackmennewstyle** [comment]
I imagine the issue here is the code not being compatible with python3 :/

**Comment by blackmennewstyle** [comment]
Misleading `Python >=2.6` got me i guess.
