### ISSUE TITLE
v3.0.0 - Team Red Miner - Unhandled Error

### ISSUE THREAD

**Issue by blackmennewstyle** [vertcoin-project/p2pool-vtc#55]
I am trying to mine using `v3.0.0.` but i am getting this error, each time the miner `Team Red Miner` tried to connect to P2POOL
```
Unhandled Error
Traceback (most recent call last):
  File "/home/ceedii/p2pool-vtc/p2pool/main.py", line 687, in run
    reactor.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1292, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 913, in runUntilCurrent
    call.func(*call.args, **call.kw)
--- <exception caught here> ---
  File "/home/ceedii/p2pool-vtc/p2pool/bitcoin/stratum.py", line 38, in _send_work
    x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
  File "/home/ceedii/p2pool-vtc/p2pool/bitcoin/worker_interface.py", line 129, in get_work
    x, handler = self._inner.get_work(*args)
  File "/home/ceedii/p2pool-vtc/p2pool/work.py", line 273, in get_work
    raise jsonrpc.Error_for_code(-12345)(u'unknown rule activated')
p2pool.util.jsonrpc.NarrowError: -12345 unknown rule activated
```
The command used with `Team Red Miner`

```
sudo /home/ceedii/teamredminer-v0.10.4-linux/teamredminer --api_listen=192.168.0.14:4459 -a verthash -o stratum+tcp://192.168.0.10:9171 -u vtc1xxxxxxxxxxxxxxxxxxxxxxxxxxxxx -p x -d 0,1,2,3,4 --verthash_file=verthash.dat --watchdog_disabled

Team Red Miner version 0.10.4
[2022-10-11 14:32:31] Auto-detected AMD OpenCL platform 1
[2022-10-11 14:32:31] Initializing GPU 0.
[2022-10-11 14:32:32] Initializing GPU 1.
[2022-10-11 14:32:33] Initializing GPU 2.
[2022-10-11 14:32:33] Initializing GPU 3.
[2022-10-11 14:32:34] Initializing GPU 4.
[2022-10-11 14:32:34] Verthash: Attempting to load data file 'verthash.dat'
[2022-10-11 14:32:35] Verthash: Data file successfully read, beginning verification.
[2022-10-11 14:32:38] Verthash: Data file verified successfully.
[2022-10-11 14:32:38] Pool 192.168.0.10 connecting to address 192.168.0.10.
[2022-10-11 14:32:38] Runtime Command Keys: h - help, s - stats, e - enable gpu, d - disable gpu, q - quit
[2022-10-11 14:32:38] API initialized on 192.168.0.14:4459
[2022-10-11 14:32:38] Watchdog thread starting.
[2022-10-11 14:32:38] Pool 192.168.0.10 successfully connected to address 192.168.0.10.
[2022-10-11 14:32:38] Successfully initialized GPU 0: Navi with 36 CU (PCIe 03:00.0) 
[2022-10-11 14:32:38] GPU 0 Uploading verthash table to gpu.
[2022-10-11 14:32:38] Successfully initialized GPU 1: Navi with 36 CU (PCIe 07:00.0) 
[2022-10-11 14:32:38] Successfully initialized GPU 2: Navi with 36 CU (PCIe 0b:00.0) 
[2022-10-11 14:32:38] Successfully initialized GPU 3: Navi with 40 CU (PCIe 0f:00.0) 
[2022-10-11 14:32:38] Successfully initialized GPU 4: Navi with 36 CU (PCIe 12:00.0) 
[2022-10-11 14:32:38] Pool 192.168.0.10 successfully subscribed. (4 ms)
[2022-10-11 14:32:38] Pool 192.168.0.10 connection was closed by the pool.
[2022-10-11 14:32:38] GPU 1 Uploading verthash table to gpu.
[2022-10-11 14:32:38] GPU 2 Uploading verthash table to gpu.
[2022-10-11 14:32:38] GPU 3 Uploading verthash table to gpu.
[2022-10-11 14:32:39] Dev pool connected and ready.
[2022-10-11 14:32:41] GPU 4 Uploading verthash table to gpu.
[2022-10-11 14:32:41] GPU 0 Verthash init completed.
[2022-10-11 14:32:41] GPU 1 Verthash init completed.
[2022-10-11 14:32:41] GPU 2 Verthash init completed.
[2022-10-11 14:32:42] GPU 3 Verthash init completed.
[2022-10-11 14:32:44] GPU 4 Verthash init completed.
[2022-10-11 14:32:53] Pool 192.168.0.10 connecting to address 192.168.0.10.
[2022-10-11 14:32:53] Pool 192.168.0.10 successfully connected to address 192.168.0.10.
[2022-10-11 14:32:53] Pool 192.168.0.10 successfully subscribed. (2 ms)
[2022-10-11 14:32:53] Pool 192.168.0.10 connection was closed by the pool.
[2022-10-11 14:33:08] Pool 192.168.0.10 connecting to address 192.168.0.10.
```
I imagine, it's probably an error on the side of the miner :/

**Comment by vertiond** [comment]
Resolved by https://github.com/vertcoin-project/p2pool-vtc/pull/53 I believe. The unknown rule being the taproot softfork.
